name: CI Build

on: [push, pull_request]

env:
  DOTNET_CLI_TELEMETRY_OPTOUT: true
  DOTNET_NOLOGO: true

jobs:
  build-test-win:
    timeout-minutes: 60
    name: Build and Test (${{ matrix.os }})
    runs-on: ${{ matrix.os }}

    strategy:
     fail-fast: false
     matrix:
      os:
        - windows-2025
      dotnet:
        - 10.0.x
    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 50
        lfs: 'true'
    - run: git fetch --tags

    - name: Setup .NET
      uses: actions/setup-dotnet@v5
      with:
        dotnet-version: ${{ matrix.dotnet }}

    - name: Restore dependencies
      run: dotnet restore

    - name: Build
      run: dotnet build -c Release --no-restore

    - name: Test
      timeout-minutes: 30
      run: dotnet test -c Release --no-restore --logger "console;verbosity=detailed" --blame-hang --blame-hang-timeout 2m --blame-hang-dump-type full

  build-test-crossplatform:
    timeout-minutes: 60
    name: Build and Test (${{ matrix.os }})
    runs-on: ${{ matrix.os }}

    strategy:
     fail-fast: false
     matrix:
      os:
        - ubuntu-24.04
        - macos-15
      dotnet:
        - 10.0.x
    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 50
        lfs: 'true'
    - run: git fetch --tags

    - name: Setup .NET
      uses: actions/setup-dotnet@v5
      with:
        dotnet-version: ${{ matrix.dotnet }}

    - name: Restore dependencies
      run: dotnet restore

    - name: Build
      run: dotnet build -c Release --no-restore

    - name: Test
      timeout-minutes: 30
      run: dotnet test -c Release --no-restore -f net10.0 --logger "console;verbosity=detailed" --blame-hang --blame-hang-timeout 2m --blame-hang-dump-type full
